language: node_js

branches:
  only: 
    - master

services:
  - postgresql
  - redis-server

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn install

before_script:
  - psql -c 'create database sinavia;' -U postgres
  - psql -c 'create database sinavia_test;' -U postgres
  - cp .env-sample .env
  - sed -ri 's/^APP_BASE_URL=/APP_BASE_URL=\$APP_BASE_URL/' .env
  - sed -ri 's/^APP_VERSION=/APP_VERSION=\$APP_VERSION/' .env
  - sed -ri 's/^API_SWAGGER=/API_SWAGGER=\$API_SWAGGER/' .env
  - sed -ri 's/^DATABASE_URL_TEST=/DATABASE_URL_TEST=\$DATABASE_URL_TEST/' .env
  - sed -ri 's/^DATABASE_URL_STAGING=/DATABASE_URL_STAGING=\$DATABASE_URL_STAGING/' .env
  - sed -ri 's/^DATABASE_URL_PRODUCTION=/DATABASE_URL_PRODUCTION=\$DATABASE_URL_PRODUCTION/' .env
  - sed -ri 's/^PORT=/PORT=\$PORT/' .env
  - sed -ri 's/^TIMEZONE=/TIMEZONE=\$TIMEZONE/' .env
  - sed -ri 's/^SECRET=/SECRET=\$SECRET/' .env

script:
  - yarn test
