language: node_js

branches:
  only: 
    - master

services:
  - postgresql
  - redis-server

cache: npm

before_install:
  - npm install

before_script:
  - psql -c 'create database sinavia;' -U postgres
  - psql -c 'create database sinavia_test;' -U postgres
  - cp .env-example .env.test
  # APP CONFIG
  - sed -ri 's/^APP_BASE_URL=/APP_BASE_URL=\$APP_BASE_URL/' .env.test
  - sed -ri 's/^APP_VERSION=/APP_VERSION=\$APP_VERSION/' .env.test
  - sed -ri 's/^API_SWAGGER=/API_SWAGGER=\$API_SWAGGER/' .env.test
  - sed -ri 's/^PORT=/PORT=\$PORT/' .env.test
  - sed -ri 's/^TIMEZONE=/TIMEZONE=\$TIMEZONE/' .env.test
  - sed -ri 's/^SECRET=/SECRET=\$SECRET/' .env.test
  # DATABASE CONFIG
  - sed -ri 's/^DATABASE_URL=/DATABASE_URL=\$DATABASE_URL/' .env.test
  - sed -ri 's/^DATABASE_USER=/DATABASE_USER=\$DATABASE_USER/' .env.test
  - sed -ri 's/^DATABASE_PASSWORD=/DATABASE_PASSWORD=\$DATABASE_PASSWORD/' .env.test
  - sed -ri 's/^DATABASE_SSL_ENABLED=/DATABASE_SSL_ENABLED=\$DATABASE_SSL_ENABLED/' .env.test
  # AWS CONFIG
  - sed -ri 's/^AWS_QUESTION_BUCKET=/AWS_QUESTION_BUCKET=\$AWS_QUESTION_BUCKET/' .env.test
  - sed -ri 's/^AWS_REGION=/AWS_REGION=\$AWS_REGION/' .env.test
  - sed -ri 's/^AWS_ACCESS_KEY_ID=/AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID/' .env.test
  - sed -ri 's/^AWS_ACCESS_SECRET_KEY=/AWS_ACCESS_SECRET_KEY=\$AWS_ACCESS_SECRET_KEY/' .env.test
  # FCM CONFIG
  - JSON_STRING=$( jq -n \
                    --arg ty "$TYPE" \
                    --arg pi "$PROJECT_ID" \
                    --arg pki "$PRIVATE_KEY_ID" \
                    --arg pk "$PRIVATE_KEY" \
                    --arg ce "$CLIENT_EMAIL" \
                    --arg ci "$CLIENT_ID" \
                    --arg au "$AUTH_URI" \
                    --arg tu "$TOKEN_URI" \
                    --arg apxcu "$AUTH_PROVIDER_X509_CERT_URL" \
                    --arg cxcu "$CLIENT_X509_CERT_URL" \
                    '{type: $ty, project_id: $pi, private_key_id: $pki, private_key: $pk, client_email: $ce, client_id: $ci, auth_uri: $au, token_uri: $tu, auth_provider_x509_cert_url: $apxcu, client_x509_cert_url: $cxcu}' )
  - echo $JSON_STRING > fcmCredentials.test.json
  - npm run db:reset

script:
  - npm run test:test
